// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/customers/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/[id].put').default>>>>
    }
    '/api/customers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/customers/index.post').default>>>>
    }
    '/api/finance/payables/:id/payment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/payables/[id]/payment.post').default>>>>
    }
    '/api/finance/payables': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/payables/index.get').default>>>>
    }
    '/api/finance/receivables/:id/payment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/receivables/[id]/payment.post').default>>>>
    }
    '/api/finance/receivables': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/receivables/index.get').default>>>>
    }
    '/api/finance/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/finance/reports/index.get').default>>>>
    }
    '/api/inventory/adjust': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/adjust.post').default>>>>
    }
    '/api/inventory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/index.get').default>>>>
    }
    '/api/inventory/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/inventory/transactions.get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.post').default>>>>
    }
    '/api/purchase/orders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchase/orders/[id].get').default>>>>
    }
    '/api/purchase/orders/:id/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchase/orders/[id]/confirm.post').default>>>>
    }
    '/api/purchase/orders/:id/receive': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchase/orders/[id]/receive.post').default>>>>
    }
    '/api/purchase/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchase/orders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/purchase/orders/index.post').default>>>>
    }
    '/api/roles/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/[id].put').default>>>>
    }
    '/api/roles': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/roles/index.post').default>>>>
    }
    '/api/sales/orders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/orders/[id].get').default>>>>
    }
    '/api/sales/orders/:id/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/orders/[id]/confirm.post').default>>>>
    }
    '/api/sales/orders/:id/ship': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/orders/[id]/ship.post').default>>>>
    }
    '/api/sales/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/orders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sales/orders/index.post').default>>>>
    }
    '/api/suppliers/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/suppliers/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/suppliers/[id].put').default>>>>
    }
    '/api/suppliers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/suppliers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/suppliers/index.post').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].put').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@_e7745a9046656ecf89dd2b1f4b1994e6/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}