// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.2_magicast_7647eb3ced70f485b4f6c2f7f86872f4/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@1.6.0/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@1.6.0/node_modules/@nuxtjs/supabase/dist/runtime/plugins/supabase.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.11.2_magicast_7647eb3ced70f485b4f6c2f7f86872f4/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.6.2_vite@5_9ed5271f37ce1b318d644a7c5f7e8033/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+devtools@2.6.2_vite@5_9ed5271f37ce1b318d644a7c5f7e8033/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+supabase@1.6.0/node_modules/@nuxtjs/supabase/dist/runtime/plugins/auth-redirect.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@3.3.2_@babel+parse_fc2567205dca72313143950e083857cd/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@3.5.2_magicast@0.3.5/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@_e7745a9046656ecf89dd2b1f4b1994e6/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_849fc79d9973a96bd5f1f162c15a0e20/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'supabase' | 'supabase' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'auth-redirect' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
