// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/8/22 00:14:15
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/60279/Desktop/erp/erp_nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/plugins/**/*.{js,ts,mjs}","C:/Users/60279/Desktop/erp/erp_nuxt/app/composables/**/*.{js,ts,mjs}","C:/Users/60279/Desktop/erp/erp_nuxt/app/utils/**/*.{js,ts,mjs}","C:/Users/60279/Desktop/erp/erp_nuxt/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/60279/Desktop/erp/erp_nuxt/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;