export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, mergeModels, toValue, useModel, useAttrs, useCssModule, useCssVars, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useAuth } from '../app/composables/useAuth';
export { useBOM } from '../app/composables/useBOM';
export { useCustomers } from '../app/composables/useCustomers';
export { useDatabase } from '../app/composables/useDatabase';
export { useDbInit } from '../app/composables/useDbInit';
export { useDepartments } from '../app/composables/useDepartments';
export { useDictionaries, Dictionary, DictionaryItem } from '../app/composables/useDictionaries';
export { useFormValidation } from '../app/composables/useFormValidation';
export { useGlobalLoading, LoadingTasks, LoadingMessages } from '../app/composables/useGlobalLoading';
export { useInventory, InventoryItem, InventoryMovement, InventoryStats } from '../app/composables/useInventory';
export { useMenus } from '../app/composables/useMenus';
export { usePayments, Payment } from '../app/composables/usePayments';
export { usePermissions } from '../app/composables/usePermissions';
export { usePositions, Position } from '../app/composables/usePositions';
export { useProduction } from '../app/composables/useProduction';
export { useProductionPlans } from '../app/composables/useProductionPlans';
export { useProductionReports } from '../app/composables/useProductionReports';
export { usePurchaseOrders, PurchaseOrderFilters } from '../app/composables/usePurchaseOrders';
export { usePurchaseReports } from '../app/composables/usePurchaseReports';
export { useReceipts, Receipt } from '../app/composables/useReceipts';
export { useResources } from '../app/composables/useResources';
export { useRoles } from '../app/composables/useRoles';
export { useSalesOrders, OrderFilters } from '../app/composables/useSalesOrders';
export { useSalesReports } from '../app/composables/useSalesReports';
export { useProducts, supabase } from '../app/composables/useSupabase';
export { useSuppliers } from '../app/composables/useSuppliers';
export { useSystemLogs, SystemLog, LogStats } from '../app/composables/useSystemLogs';
export { useTheme } from '../app/composables/useTheme';
export { useUsers } from '../app/composables/useUsers';
export { useWorkshops } from '../app/composables/useWorkshops';
export { devLog, safeAction, safeAsyncAction, confirmAction, alertMessage, isDevelopment, isProduction, devOnly, isNotNull, isString, isNumber, isObject, isArray, safeGet, delay, generateId, formatDate, formatDateTime, formatAmount, truncateText } from '../app/utils/dev-tools';
export { ErrorCode, ErrorCode, createAppError, parseError, isAppError, ErrorHandler, ErrorHandler, handleError, handleAsyncError, AppError } from '../app/utils/error-handler';
export { LogLevel, LogLevel, logger, log } from '../app/utils/logger';
export { perf, logMemoryUsage, logPageLoadMetrics, logResourceMetrics, measureApiCall, measureComponentRender, debounce, throttle, memoize, batchProcess } from '../app/utils/performance';
export { useSupabaseClient } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.1/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseClient';
export { useSupabaseCookieRedirect } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.1/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseCookieRedirect';
export { useSupabaseSession } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.1/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseSession';
export { useSupabaseUser } from '../node_modules/.pnpm/@nuxtjs+supabase@1.6.1/node_modules/@nuxtjs/supabase/dist/runtime/composables/useSupabaseUser';
export { useNuxtDevTools } from '../node_modules/.pnpm/@nuxt+devtools@2.6.3_vite@7_c09d661678d69ff4d617d5d3248da503/node_modules/@nuxt/devtools/dist/runtime/use-nuxt-devtools';
export { definePageMeta } from '../node_modules/.pnpm/nuxt@4.0.3_@netlify+blobs@9_91bee25a2dcd7b3e544a45cdb9d9cf74/node_modules/nuxt/dist/pages/runtime/composables';